### ISSUE TITLE
Windows Docker Image

### ISSUE THREAD

**Issue by yasin06** [geotekne-argentina/osm-geoserver-postgis#1]
Hi, since windows support is a TODO, can you consider changing docker files to run shell scripts inside docker images, so we can use docker-compose on windows?
Best regards =)

**Comment by jemacchi** [comment]
Hi ! 
The script that requires adjustments in order to allow a proper initialization is the one called [startup.sh](https://github.com/geotekne-argentina/osm-geoserver-postgis/blob/master/startup.sh).

That script initializes required data in postgis (using imposm scripts). The idea of having that inside of the docker image for Postgis is not bad (despite it would be only for the purpose of OSM importation process running from container).
When possible, I will take that approach and adjust it (but, if you would want to push a fix/improvement on that, you are welcome)

Regards

**Comment by yasin06** [comment]
Hi, I succeeded it doing manually, if you can give me permissions on the repository I can make a contribution on the script any time possible. Best Regards.

**Comment by jemacchi-devbase** [comment]
hi @yasin06 sorry for log delay to response
If you have some extra scripting ready for the Windows version, please follow this instructions regarding how to contribute on the repo.
english version: https://www.dataschool.io/how-to-contribute-on-github/
spanish version (shorter description):  https://gist.github.com/BCasal/026e4c7f5c71418485c1

Essentially, it's the same way of working for any OS project.
1. Fork the project
2. Clone it
3. Add the upstream repository to your fork
4. Get updates from the upstream main
5. Create your branch
6. Apply your changes & push them
7. Compare and create a pull request (PR)

Once we get the PR, then we can review and push it into the main repo. 
I know it's a little more complex than just sharing permissions on the repo, but you also surely understand that we need to make it safe (btw, it's nothing different from other projects too). The extra steps are those from 1 to 4 (fork and upstream definition).

If any doubt, just write me. I will be glad of helping you with that.

**Comment by jemacchi** [comment]
hi @yasin06 sorry for log delay to response
If you have some extra scripting ready for the Windows version, please follow this instructions regarding how to contribute on the repo.

- english version: https://www.dataschool.io/how-to-contribute-on-github/
- spanish version (shorter description): https://gist.github.com/BCasal/026e4c7f5c71418485c1
 
Essentially, it's the same way of working for any OS project.

1. Fork the project
2. Clone it
3. Add the upstream repository to your fork
4. Get updates from the upstream main
5. Create your branch
6. Apply your changes & push them
7. Compare and create a pull request (PR)

Once we get the PR, then we can review and push it into the main repo.
I know it's a little more complex than just sharing permissions on the repo, but you also surely understand that we need to make it safe (btw, it's nothing different from other projects too). The extra steps are those from 1 to 4 (fork and upstream definition).

If any doubt, just write me. I will be glad of helping you with that.

**Comment by jemacchi** [comment]
Hi @yasin06 ! update: I finally created a version on which you don't have to take care of imposm scripts (that allows ingest PBFs files into the Postgis). So, now you only need git, docker and docker-compose installed on your system and it works (and that means that you can run it on Windows, if you have those tools installed).  
Any feedback will be welcome.
