### ISSUE TITLE
osm-lowres is no longer available. access denied.

### ISSUE THREAD

**Issue by jeffreyschultz** [geotekne-argentina/osm-geoserver-postgis#3]
The osm-lowres geopackage is no longer available for download from that provider.

**Comment by jemacchi** [comment]
hi @jeffreyschultz, yes, the storj.io storage credits was fully used so now need to add some $. Thanks for noticing and let me know. As soon as added some credits I will let you know.

**Comment by jemacchi** [comment]
Hi @jeffreyschultz whenever you want, give a try. Now storj.io account was unblocked ! (officially I will have to start looking for funding, LOL). For now, just enjoy it.

In case you like the idea of having you own cloudless satellital basemap, then you can try this repo  https://github.com/geotekne-argentina/satellite-geoserver (I'm sharing a selection of prepared gkpg with tiles for levels 11 to 15.   https://link.storjshare.io/s/jucmb3pzqxtuyu5a4xk2j3se2afa/satellite/  )

And if you like the idea of your own basemaps setup (street, satellital, hybrid), then check this repo https://github.com/geotekne-argentina/all-basemaps-geoserver   (I'm still working on some documentation or/and adjustments, but you can see how it works here https://www.youtube.com/watch?v=PQFKiLogSxM )

**Comment by jeffreyschultz** [comment]
@jemacchi Thank you for the response. It took me a while to get back around to this. I am checking the links out now. :)
