### ISSUE TITLE
Data not imported when running startup.sh

### ISSUE THREAD

**Issue by phillashworth** [geotekne-argentina/osm-geoserver-postgis#5]
I ran `setup-datasets.sh` and the data was downloaded correctly but when I run `startup.sh` the Docker containers all start up immediately without error but I suspect the data isn't actually getting imported to PostGIS. 

In the demo client I get this error:

```
<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.3.0" xsi:schemaLocation="http://www.opengis.net/ogc http://localhost:8080/geoserver/schemas/wms/1.3.0/exceptions_1_3_0.xsd">
<ServiceException> java.lang.RuntimeException: java.io.IOException: Schema 'osm_landusages' does not exist. java.io.IOException: Schema 'osm_landusages' does not exist. Schema 'osm_landusages' does not exist. </ServiceException>
</ServiceExceptionReport>
```

**Comment by jemacchi** [comment]
hi @phillashworth , Yes, depending on which dataset you are importing (and hardware and so on), importation process could be still running and so geoserver is going to show that kind of messages.
Check this issue  https://github.com/geotekne-argentina/osm-geoserver-postgis/issues/4

It will provide some info about same situation (and it's something that I will have to work -kind of log or messages during setup- or maybe just documentation, to let users know in advance about it)

**Comment by phillashworth** [comment]
Thanks @jemacchi I didn't realise it was silently importing the data.
It's all up and running now :)

**Comment by jemacchi** [comment]
I will add some task regarding that (logging or doc or warning about that). Thanks !
